[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wapp"
version = "0.1.0"
description = "A modular Flask API framework with auto CRUD and migrations"
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
authors = [
  {name = "saitech"}
]
dependencies = [
  "alembic",
  "python-dotenv",
  "flask",
  "sqlalchemy"
]

[project.urls]
Homepage = "https://github.com/saitech-org/wapp"

