[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "saitech-wapp"
version = "0.1.0"
description = "A modular Flask API framework with auto CRUD and migrations"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{ name = "saitech" }]
dependencies = [
  "alembic",
  "python-dotenv",
  "flask",
  "sqlalchemy"
]

[project.urls]
Homepage = "https://github.com/saitech-org/wapp"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
