name: Publish on Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Match the environment name you approved on PyPI ("pypi" in your screenshot)
    environment:
      name: pypi

    permissions:
      contents: read
      id-token: write  # REQUIRED for PyPI Trusted Publishing (OIDC)

    steps:
      - name: Check out code at release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
