# If you prefer publishing when a GitHub Release is published, use this instead:
name: Publish on Release

permissions:
  contents: read
  id-token: write

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub context
        run: |
          echo "Actor:        $GITHUB_ACTOR"
          echo "Repository:   $GITHUB_REPOSITORY"
          echo "Workflow:     $GITHUB_WORKFLOW"
          echo "Ref:          $GITHUB_REF"
          echo "Ref type:     $GITHUB_REF_TYPE"
          echo "SHA:          $GITHUB_SHA"
      - name: Test GitHub token
        run: |
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/$GITHUB_REPOSITORY \
            | jq '.full_name, .private, .permissions'
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip && pip install build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
